-- Inserts para tb_especie (sem especificar ID, pois é autogerado)
INSERT INTO tb_especie (nome) VALUES 
('Cachorro'),
('Gato'),
('Coelho'),
('Pássaro'),
('Peixe'),
('Hamster'),
('Cavalo'),
('Porquinho-da-índia'),
('Tartaruga'),
('Lagarto');

-- Inserts para tb_animal (usando os IDs correspondentes das espécies inseridas acima)
INSERT INTO tb_animal (nome, pelagem, peso, foto, idade, especie_id) VALUES 
('Bidu', 'Encaracolada', 8.5, 'bidu.jpg', 4, 1),
('Rex', 'Curta', 25.0, 'rex.jpg', 6, 1),
('Luna', 'Longa', 30.0, 'luna.jpg', 5, 1),
('Thor', 'Curta', 28.0, 'thor.jpg', 4, 1),
('Mel', 'Sedosa', 6.5, 'mel.jpg', 3, 1),
('Mia', 'Fofa', 5.2, 'mia.jpg', 3, 2),
('Simba', 'Longa', 6.0, 'simba.jpg', 4, 2),
('Nick', 'Curta', 40.0, 'nick.jpg', 6, 1),
('Lili', 'Lisa', 4.0, 'lili.jpg', 5, 2),
('Fred', 'Curta', 26.0, 'fred.jpg', 4, 1),
('Zoe', 'Lisa', 3.2, 'zoe.jpg', 2, 1),
('Bruce', 'Espessa', 32.0, 'bruce.jpg', 5, 1),
('Tina', 'Longa', 4.8, 'tina.jpg', 3, 2),
('Rocky', 'Densa', 28.5, 'rocky.jpg', 4, 1),
('Maggie', 'Lisa', 7.0, 'maggie.jpg', 3, 1),
('Pepe', 'Sedosa', 1.0, 'pepe.jpg', 2, 3),
('Cacau', 'Fofa', 5.5, 'cacau.jpg', 3, 1),
('Max', 'Lisa', 35.0, 'max.jpg', 5, 1),
('Jade', 'Sedosa', 7.2, 'jade.jpg', 4, 1),
('Bolt', 'Encaracolada', 19.0, 'bolt.jpg', 3, 1),
('Bela', 'Lisa', 10.2, 'bela.jpg', 4, 1),
('Snow', 'Fofa', 25.5, 'snow.jpg', 5, 1),
('Léo', 'Lisa', 6.1, 'leo.jpg', 2, 1),
('Nico', 'Curta', 29.0, 'nico.jpg', 5, 1),
('Amy', 'Ondulada', 14.0, 'amy.jpg', 4, 1),
('Ozzy', 'Densa', 27.0, 'ozzy.jpg', 6, 1),
('Lua', 'Mista', 8.3, 'lua.jpg', 3, 2),
('Kira', 'Lisa', 7.5, 'kira.jpg', 4, 2),
('Theo', 'Longa', 6.2, 'theo.jpg', 3, 2),
('Melody', 'Sedosa', 5.9, 'melody.jpg', 2, 2),
('Bobinho', 'Raspada', 9.0, 'bobinho.jpg', 5, 2),
('Bolinha', 'Manchada', 4.3, 'bolinha.jpg', 2, 2),
('Pretinha', 'Preta', 7.1, 'pretinha.jpg', 3, 2),
('Tigrão', 'Tigrada', 6.8, 'tigrao.jpg', 4, 2),
('Pingo', 'Lisa', 3.5, 'pingo.jpg', 2, 2),
('Fofuxo', 'Encaracolada', 10.0, 'fofuxo.jpg', 5, 2),
('Sushi', 'Lisa', 2.8, 'sushi.jpg', 1, 2),
('Jujuba', 'Rugosa', 6.6, 'jujuba.jpg', 3, 2),
('Gato', 'Sem pelos', 3.9, 'gato.jpg', 2, 2),
('Sandy', 'Longa', 5.7, 'sandy.jpg', 3, 2),
('Café', 'Lisa', 6.0, 'cafe.jpg', 4, 2),
('Latinha', 'Fofa', 4.4, 'latinha.jpg', 2, 2),
('Tigre', 'Tigrada', 5.5, 'tigre.jpg', 3, 2),
('Chocolate', 'Lisa', 8.0, 'chocolate.jpg', 4, 2),
('Menta', 'Lisa', 3.2, 'menta.jpg', 2, 2),
('Amora', 'Ondulada', 4.9, 'amora.jpg', 2, 2),
('Sonic', 'Curta', 0.8, 'sonic.jpg', 1, 6),
('Tico', 'Colorida', 0.2, 'tico.jpg', 2, 4),
('Nemo', 'Escamosa', 0.1, 'nemo.jpg', 1, 5),
('Speed', 'Sem pelagem', 12.0, 'speed.jpg', 10, 9),
('Lagartixa', 'Escamosa', 0.5, 'lagartixa.jpg', 3, 10);
